# Google App Engine configuration (if you choose Option 2)
runtime: nodejs20

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

env_variables:
  NODE_ENV: "production"
  # Add your other environment variables here or use .env.yaml

# Handlers for static files if needed
handlers:
  - url: /.*
    script: auto
    secure: always
